name: apple_id_auth
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  asn1lib: ^1.5.8
  auto_route: ^9.2.2
  crypto: ^3.0.6
  cryptography: ^2.7.0
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.1.1
  dio: ^5.7.0
  encrypt: ^5.0.3
  equatable: ^2.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_secure_storage: ^4.2.1
  get_it: ^8.0.2
  pointycastle: ^3.9.1
  sign_in_with_apple: ^6.1.3
  uuid: ^4.5.1
  very_good_analysis: ^6.0.0

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
